#ifndef __NetTypes__
#define __NetTypes__

#define NETTYPE_PAYCHECK1 0x00
#define NETTYPE_PAYCHECK2 0x01
#define NETTYPE_AUTHORIZATION 0x02
#define NETTYPE_PING 0x05
#define NETTYPE_COMMAND 0x0A
#define NETTYPE_SIGN 0x0B
#define NETTYPE_UNSIGN 0x0C
#define NETTYPE_GETUSERS 0x16
#define NETTYPE_PAYCHECK3 0xB0

#endif

